const oauth = '' 
const youtube = '' 
const randomTrack = '' 
const randomFact = 'https://uselessfacts.jsph.pl/random.json?language=en' 
const chat = 'https://some-random-api.ml/chatbot?message=' 
const locate = '' 
const geonames = 'http://api.geonames.org/searchJSON?q=+' 
const nasa1 = 'https://api.nasa.gov/neo/rest/v1/feed?start_date=' 
const nasa2 = '' 
const twitter = 'https://decapi.me/twitter/latest/' 
const hosts = 'https://decapi.me/twitch/hosts/' 
const bttv = 'https://decapi.me/bttv/emotes/' 
const joke1 = 'https://official-joke-api.appspot.com/jokes/programming/random' 
const joke2 = 'https://official-joke-api.appspot.com/random_joke'  
const rl = 'https://api.gempir.com/channel/' 
const joemama = 'https://api.yomomma.info/' 
const supinic = '' 
const dubtrackRoom = '' 
const discord = '' 

module.exports = {oauth, youtube, randomTrack, randomFact, chat, locate, geonames, nasa1, nasa2, twitter, hosts, bttv, joke1, joke2, rl, joemama, supinic, dubtrackRoom, discord}