kind: Service
apiVersion: v1
metadata:
  name: kbot-api
  labels:
    app: kbot-api
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: kbot-api
  type: NodePort

