apiVersion: apps/v1
kind: Deployment
metadata:
  name: kbot-mirrors-reddit-live-thread-to-discord
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kbot-mirrors-reddit-live-thread-to-discord
  template:
    metadata:
      labels:
        app: kbot-mirrors-reddit-live-thread-to-discord
    spec:
      containers:
        - name: kbot-mirrors-reddit-live-thread-to-discord
          image: docker-registry.app.kunszg.com/kbot-mirrors:latest
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: kbot-config
          env:
            - name: APP_NAME
              value: "REDDIT_LIVE_THREAD_TO_DISCORD"
      imagePullSecrets:
        - name: regcred-v1
