apiVersion: apps/v1
kind: Deployment
metadata:
  name: kbot-mirrors-twitch-chat-message-logger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kbot-mirrors-twitch-chat-message-logger
  template:
    metadata:
      labels:
        app: kbot-mirrors-twitch-chat-message-logger
    spec:
      containers:
        - name: kbot-mirrors-twitch-chat-message-logger
          image: docker-registry.app.kunszg.com/kbot-mirrors:latest
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: kbot-config
          env:
            - name: APP_NAME
              value: "TWITCH_CHAT_MESSAGE_LOGGER"
      imagePullSecrets:
        - name: regcred-v1
