apiVersion: apps/v1
kind: Deployment
metadata:
  name: kbot-mirrors-update-emotes-list
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kbot-mirrors-update-emotes-list
  template:
    metadata:
      labels:
        app: kbot-mirrors-update-emotes-list
    spec:
      containers:
        - name: kbot-mirrors-update-emotes-list
          image: docker-registry.app.kunszg.com/kbot-mirrors:latest
          imagePullPolicy: Always
          volumeMounts:
            - name: node-modules-volume
              mountPath: /usr/src/app/node_modules
          envFrom:
            - configMapRef:
                name: kbot-config
          env:
            - name: APP_NAME
              value: "UPDATE_EMOTES_LIST"
      imagePullSecrets:
        - name: regcred-v1
      volumes:
        - name: node-modules-volume
          hostPath:
            path: /home/docker/kbot/node_modules
            type: Directory
