apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: logging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      securityContext:
        fsGroup: 472
        runAsUser: 472
      containers:
        - name: grafana
          image: grafana/grafana:10.2.0
          ports:
            - containerPort: 3005
          resources:
            limits:
              memory: 512Mi
              cpu: 300m
            requests:
              memory: 256Mi
              cpu: 150m
          env:
#            - name: GF_SECURITY_ADMIN_USER
#              value: "user"
#            - name: GF_SECURITY_ADMIN_PASSWORD
#              value: "pass"
            - name: GF_USERS_ALLOW_SIGN_UP
              value: "false"
            - name: GF_SERVER_HTTP_PORT
              value: "3005"
          volumeMounts:
            - name: grafana-storage
              mountPath: /var/lib/grafana
            - name: grafana-datasources
              mountPath: /etc/grafana/provisioning/datasources
          readinessProbe:
            httpGet:
              path: /api/health
              port: 3005
            initialDelaySeconds: 30
            timeoutSeconds: 2
      volumes:
        - name: grafana-storage
          hostPath:
            path: /tmp/grafana-storage
        - name: grafana-datasources
          configMap:
            name: grafana-datasources