kind: Service
apiVersion: v1
metadata:
  name: redis-clusterip
  namespace: default
spec:
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  selector:
    app: redis
  type: ClusterIP