apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: default
  labels:
    app: mysql
spec:
  serviceName: "mysql-clusterip"
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      volumes:
        - name: mysql-storage
          hostPath:
            path: /home/docker/mysql
      containers:
        - name: mysql
          image: mysql:8.0.36
          ports:
            - name: mysql
              containerPort: 3306
              protocol: TCP
          envFrom:
            - configMapRef:
                name: mysql-server-config
          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
