apiVersion: apps/v1
kind: Deployment
metadata:
  name: j-music-bot
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: music-bot
  template:
    metadata:
      labels:
        app: music-bot
    spec:
      containers:
        - name: music-bot
          image: docker-registry.kunszg.com/kbot-depl-music-bot:latest
          imagePullPolicy: Always
          volumeMounts:
            - name: config-volume
              mountPath: /usr/src/app/music-bot/config.txt
            - name: server-settings-volume
              mountPath: /usr/src/app/music-bot/serversettings.json
            - name: playlists-volume
              mountPath: /usr/src/app/music-bot/Playlists
            - name: youtubetoken-volume
              mountPath: /usr/src/app/music-bot/youtubetoken.txt
      imagePullSecrets:
        - name: regcred-v1
      volumes:
        - name: config-volume
          hostPath:
            path: /home/docker/musicbot/config.txt
            type: File
        - name: server-settings-volume
          hostPath:
            path: /home/docker/musicbot/serversettings.json
            type: File
        - name: playlists-volume
          hostPath:
            path: /home/docker/musicbot/Playlists
        - name: youtubetoken-volume
          hostPath:
            path: /home/docker/musicbot/youtubetoken.txt

