apiVersion: apps/v1
kind: Deployment
metadata:
  name: kbot-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kbot-api
  template:
    metadata:
      labels:
        app: kbot-api
    spec:
      containers:
        - name: kbot-api
          image: docker-registry.app.kunszg.com/kbot-api:latest
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: kbot-config
      imagePullSecrets:
        - name: regcred-v1
